// <auto-generated />
using System;
using ChatTask.ChatService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatTask.ChatService.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20250911200737_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatTask.ChatService.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name");

                    b.ToTable("Conversations");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId", "ParentId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ThreadId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.Channel", b =>
                {
                    b.HasBaseType("ChatTask.ChatService.Models.Conversation");

                    b.Property<bool>("AutoAddNewMembers")
                        .HasColumnType("bit");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorkspaceId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("WorkspaceId1");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.DirectMessage", b =>
                {
                    b.HasBaseType("ChatTask.ChatService.Models.Conversation");

                    b.Property<Guid>("WorkspaceId2")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("WorkspaceId2");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.Group", b =>
                {
                    b.HasBaseType("ChatTask.ChatService.Models.Conversation");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkspaceId2")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("WorkspaceId2");

                    b.ToTable("Conversations", t =>
                        {
                            t.Property("Purpose")
                                .HasColumnName("Group_Purpose");

                            t.Property("WorkspaceId2")
                                .HasColumnName("Group_WorkspaceId2");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.TaskGroup", b =>
                {
                    b.HasBaseType("ChatTask.ChatService.Models.Conversation");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskCount")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkspaceId2")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("WorkspaceId2");

                    b.ToTable("Conversations", t =>
                        {
                            t.Property("WorkspaceId2")
                                .HasColumnName("TaskGroup_WorkspaceId2");
                        });

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.Conversation", b =>
                {
                    b.HasOne("ChatTask.ChatService.Models.Workspace", "Workspace")
                        .WithMany("Conversations")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.Member", b =>
                {
                    b.HasOne("ChatTask.ChatService.Models.Conversation", null)
                        .WithMany("ConversationMembers")
                        .HasForeignKey("ConversationId");

                    b.HasOne("ChatTask.ChatService.Models.Conversation", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ChatTask.ChatService.Models.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Conversation");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.Message", b =>
                {
                    b.HasOne("ChatTask.ChatService.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.Channel", b =>
                {
                    b.HasOne("ChatTask.ChatService.Models.Workspace", null)
                        .WithMany("Channels")
                        .HasForeignKey("WorkspaceId1");
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.DirectMessage", b =>
                {
                    b.HasOne("ChatTask.ChatService.Models.Workspace", null)
                        .WithMany("DirectMessages")
                        .HasForeignKey("WorkspaceId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.Group", b =>
                {
                    b.HasOne("ChatTask.ChatService.Models.Workspace", null)
                        .WithMany("Groups")
                        .HasForeignKey("WorkspaceId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.TaskGroup", b =>
                {
                    b.HasOne("ChatTask.ChatService.Models.Workspace", null)
                        .WithMany("TaskGroups")
                        .HasForeignKey("WorkspaceId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.Conversation", b =>
                {
                    b.Navigation("ConversationMembers");

                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ChatTask.ChatService.Models.Workspace", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Conversations");

                    b.Navigation("DirectMessages");

                    b.Navigation("Groups");

                    b.Navigation("Members");

                    b.Navigation("TaskGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
